export const REPORT_CONSTANTS = {
    'URL': {
        REPORT: '/report',
        REPORT_COMPANY: '/report/company',
        REPORT_COMPANY_BUILDING: '/report/company-building',
        REPORT_VENDOR: '/report/vendor',
        REPORT_DISTRIBUTOR: '/report/distributor',
        REPORT_CLIENT_VENDOR: '/report/client-vendor',
        REPORT_CLIENT_COMPANY: '/report/client-company',
        REPORT_VENDOR_COMPANY: '/report/vendor-company',
        REPORT_VENDOR_ERROR: '/report/vendor-error',
        REPORT_COMPANY_ERROR: '/report/company-error',
    },

    LINK: {
        COMPANY: 'company',
        COMPANY_BUILDING: 'company-building',
        VENDOR: 'vendor',
        DISTRIBUTOR: 'distributor',
        CLIENT_VENDOR: 'client-vendor',
        CLIENT_COMPANY: 'client-company',
        VENDOR_COMPANY: 'vendor-company',
        VENDOR_ERROR: 'vendor-error',
        COMPANY_ERROR: 'company-error',
    },

    LABEL: {
        REPORT: 'Report',
        PRODUCT: 'Product',
        PRODUCT_LIST: 'Product List',
        REPORT_LIST: 'Report List',
        CLIENT_COMPANY_REPORT_LIST: 'Company Report List',
        COMPANY_REPORT_LIST: 'Company Report List',
        COMPANY_BUILDING_REPORT_LIST: 'Company Building Report List',
        CLIENT_VENDOR_REPORT_LIST: 'Vendor Report List',
        VENDOR_REPORT_LIST: 'Vendor Report List',
        DISTRIBUTOR_REPORT_LIST: 'Distributor Report List',
        PRODUCT_LIST_DESC: 'Product List Desc',
        REPORT_PASSWORD: 'Report Password',
        MACHINE_PRODUCT_TYPE: 'Machine Product Type',
        REPORT_IMAGE: 'Image',
        REPORT_IMAGES: 'Image',
        REPORT_COMPANY_LIST_LINK: 'report.list.pageLink',
        MACHINE_PRODUCT_LINK: 'report.list.machineProduct',
        REPORT_PRODUCT_LINK: 'report.list.reportProduct',
        NEW_REPORT_PRODUCT_LINK: 'report.list.newReportProduct',
        REPORT_COMPANY_LIST: 'report.list.pageTitle',
        REPORT_COMPANY_LIST_DESC: 'report.list.pageDesc',
        REPORT_EDIT_LINK: 'report.edit.pageLink',
        REPORT_EDIT: 'report.edit.pageTitle',
        REPORT_EDIT_DESC: 'report.edit.pageDesc',
        REPORT_VENDOR_PRODUCT_DESC: 'report.edit.vendorProductDesc',
        REPORT_SHOW_LINK: 'report.show.pageLink',
        REPORT_SHOW: 'report.show.pageTitle',
        REPORT_SHOW_DESC: 'report.show.pageDesc',
        REPORT_CREATE_LINK: 'report.create.pageLink',
        REPORT_CREATE: 'report.create.pageTitle',
        REPORT_CREATE_DESC: 'report.create.pageDesc',
        REPORT_ACTION_CREATE: 'page.action.create',
        REPORT_ACTION_CHANGE_PASSWORD: 'page.action.change_password',
        REPORT_ACTION_EDIT: 'page.action.update',
        REPORT_CHANGE_PASSWORD: 'report.changePassword.pageDesc',
        REPORT_CHANGE_PASSWORD_DESC: 'report.changePassword.pageDesc',
        REPORT_CHANGE_PASSWORD_LINK: 'report.form.changePasswordLink',


    },
    API: {
        REPORT: '/crud/Report',
        REPORTS: '/crud/Report/all',
        REPORT_ALIAS: '/crud/Report/:alias',
        REPORT_PASSWORD_ALIAS: '/crud/User/:alias',
        REPORT_STATUS: '/changeReportStatus',
        SEARCH_REPORT: '/crud/Report/search/:query',
        FILE_UPLOAD: '/device/reportImage',
        CITIES: '/crud/City/all',
        DISTRIBUTOR: '/crud/Distributor',
        DISTRIBUTORS: '/crud/Distributor/all',
        COMPANY: '/crud/Company',
        COMPANIES: '/crud/Company/all',
        VENDOR: '/crud/Vendor',
        VENDORS: '/crud/Vendor/all',
        PRODUCT_TYPE: '/crud/ProductType',
        PRODUCT_TYPES: '/crud/ProductType/all',
        PRODUCTS: '/crud/Product/all',
        MACHINE: '/crud/Machine',
        MACHINES: '/crud/Machine/all',
        ZONE: '/crud/Zone',
        ZONES: '/crud/Zone/all',
        COMPANY_BUILDINGS_DATA_COMPANY: '/crud/CompanyBuilding/all',
        // COMPANY_BUILDING_PRODUCT:'/crud/CompanyBuildingProduct?fieldName=status&value=accepted',
        // COMPANY_BUILDING_PRODUCTS:'/crud/CompanyBuildingProduct?fieldName=status&value=New',
        // COMPANY_BUILDINGS: '/crud/CompanyBuilding',
        COMPANY_BUILDING: '/crud/CompanyBuilding/all',
        // COMPANY_BUILDING_PRODUCT:'/crud/CompanyBuildingProduct?fieldName=status&value=accepted',
       //  COMPANY_BUILDING_PRODUCTS:'/crud/CompanyBuildingProduct?fieldName=status&value=New',
        ALL_COMPANY_BUILDING_PRODUCT: '/crud/CompanyBuildingProduct',
        COMPANY_BUILDING_PRODUCT_STATUS: '/crud/CompanyBuildingProduct/:alias',
        DOWNLOAD_PRODUCT_DATA_ALIAS: '/device/downloadProductDataByProductId/:alias',

        COMPANY_BUILDING_PRODUCTS: '/device/getCurrentBuildingProduct',
        COMPANY_PRODUCTS: '/device/getCurrentCompanyProduct',
        // DISTRIBUTORS_PRODUCTS:'/device/getCurrentDistributorProduct',
        DISTRIBUTOR_PRODUCTS: '/crud/DistributorProduct/all',
        // VENDORS_PRODUCTS:'/crud/VendorProduct/all',

        PRODUCT_DATA_ALIAS: '/device/getProductDataByProductId/:alias',
        PRODUCT_PRODUCT_TYPE_ALIAS: '/device/getProductByProductTypeId/:alias',
        PRODUCT: '/crud/Product',
        BUILDINGS: '/crud/CompanyBuilding/all',
        VENDOR_DATA: '/report/getData',
        DISTRIBUTOR_DATA: '/report/getData',
        DISTRIBUTORS_PRODUCTS: '/device/getCurrentDistributorProduct',
        VENDORS_PRODUCTS: '/device/getCurrentVendorProduct',
        COMPANY_BUILDINGS: '/device/getCompanyBuildingByCompanyId/:companyAlias',
        COMPANY_DATA: '/report/getData',
        CLIENT_DATA: '/report/getData',
        COMPANY_BUILDING_DATA: '/report/getData',
        COMPANY_PRODUCT: '/crud/CompanyProduct/all',
        CLIENT_PRODUCT: '/crud/ClientProduct/all',
        VENDOR_PRODUCTS: '/crud/VendorProduct/all',
        COMPANY_BUILDING_PRODUCT: '/crud/CompanyBuildingProduct/all',
        DOWNLOAD_DATA: '/report/downloadData',
        DOWNLOAD_ERROR_DATA: '/report/downloadErrorData',
        COMPANY_BUILDING_LIST: '/device/getObjectsByOwnerId/CompanyBuilding/:ownerId',
        COMPANY_LIST: '/device/getObjectsByOwnerId/Company/:ownerId',
        MACHINE_BY_BUILDING: '/device/getObjectsByOwnerId/CompanyBuildingProduct/:ownerId',
        CURRENT_PRODUCT_TYPE: '/device/getAllProductTypes',
        PRODUCT_BY_COMPANY_BUILDING: '/device/getObjectsByOwnerId/CompanyBuildingProduct/:ownerId',
        PRODUCT_BY_COMPANY_BUILDING_AND_PRODUCT_TYPE: '/device/getCompanyBuildingProducts/:ownerId/:productTypeId',
        DISTRIBUTOR_LIST: '/device/getObjectsByOwnerId/Distributor/:ownerId',
        VENDOR_OF_CLIENT: '/crud/Vendor/all',
        COMPANY_OF_CLIENT: '/crud/Company/all',
        CLIENT_VENDOR_DATA: '/report/getData',
        CLIENT_COMPANY_DATA: '/report/getData',
        CLIENT_ERROR_DATA: '/report/getErrorData',
        FOTAS: '/crud/Firmware/all',
        ERROR_DATAS: '/crud/ErrorData/all',
        TELEMETRIC_DATAS: '/crud/TelemetricData/all',
        MEDIAS: '/crud/Media/all',
        CLIENT: '/device/getClient',

    },

    FIELD: {
        NAME: 'name',
        NAME_FIELD: 'name',
        EMAIL: 'email',
        EMAIL_FIELD: 'email',
        PHONE_NUMBER: 'phoneNo',
        PHONE_NUMBER_FIELD: 'phoneNo',
        USERNAME: 'username',
        PASSWORD: 'password',
        CONFIRM_PASSWORD: 'confirmPassword'
    }
};
