export const COMPANY_CONSTANTS = {
    'URL': {
         COMPANY: '/company',
         COMPANY_LIST: '/company/list',
         COMPANY_EDIT: '/company/edit/',
         COMPANY_SHOW: '/company/show',
         COMPANY_CREATE: '/company/create',
         COMPANY_COMPANY_PRODUCT: '/company/company-product',
         COMPANY_NEW_COMPANY_PRODUCT: '/company/new-company-product',
         COMPANY_ALL_COMPANY_PRODUCT: '/company/all-company-product',
         COMPANY_ASSIGNED_COMPANY_BUILDING_PRODUCT: '/company/assigned-company-building-product',
         PRODUCT_TELEMETRIC_DATA: '/product/telemetric-data',
         PRODUCT_ERROR_DATA: '/product/error-data',
         COMPANY_CHANGE_PASSWORD: '/company/change-password',
         COMPANY_SUBSCRIPTION_LIST: '/company/subscription-list',
         COMPANY_SUBSCRIPTION_LIST_ALIAS: '/company/subscription-list/:alias',
         COMPANY_SUBSCRIPTION_EDIT: '/company/subscription-edit',
    },

    LINK: {
        LIST: 'list',
        CREATE: 'create',
        SHOW: 'show/:alias',
        EDIT: 'edit/:alias',
        COMPANY_PRODUCT: 'company-product',
        NEW_COMPANY_PRODUCT: 'new-company-product',
        ALL_COMPANY_PRODUCT: 'all-company-product',
        ASSIGNED_COMPANY_BUILDING_PRODUCT: 'assigned-company-building-product',
        TELEMETRIC_DATA: 'telemetric-data/:alias',
        ERROR_DATA: 'error-data/:alias',
        CHANGE_PASSWORD: 'change-password/:alias',
        SUBSCRIPTION_LIST: 'subscription-list/:alias',
        SUBSCRIPTION_EDIT: 'subscription-edit/:alias',
    },

    LABEL: {
        COMPANY: 'Company',
        ALL_COMPANY_LIST_LINK: 'All Company Product',
        COMPANY_PASSWORD: 'Company Password',
        COMPANY_CHANGE_PASSWORD: 'Company Change Password',
        COMPANY_CHANGE_PASSWORD_DESC: 'Change Password Detail',
        COMPANY_CHANGE_PASSWORD_LINK: 'Change Password',
        COMPANY_IMAGE: 'Image',
        COMPANY_BUILDING: 'Company Building',
        COMPANY_BUILDING_PRODUCT: 'Company Building Product',
        ASSIGNED_COMPANY_BUILDING_PRODUCT: 'Assigned Company Building Product',
        COMPANY_USER: 'CompanyUser',
        COMPANY_ADMIN: 'CompanyAdmin',
        COMPANY_LIST_LINK: 'company.list.pageLink',
        COMPANY_PRODUCT_LIST_LINK: 'company.list.companyProductList',
        COMPANY_NEW_PRODUCT_LIST_LINK: 'company.list.companyNewProduct',
        COMPANY_LIST: 'company.list.pageTitle',
        ASSIGNED_COMPANY_BUILDING_PRODUCT_LIST: 'company.list.assignedCompanyBuildingProduct',
        ASSIGNED_COMPANY_BUILDING_PRODUCT_LIST_LINK: 'company.list.assignedCompanyBuildingProductLink',
        COMPANY_LIST_DESC: 'company.list.pageDesc',
        COMPANY_COMPANY_PRODUCT_LINK: 'company.company_product.pageLink',
        COMPANY_COMPANY_PRODUCT: 'company.company_product.pageTitle',
        COMPANY_COMPANY_PRODUCT_DESC: 'company.company_product.pageDesc',
        ASSIGNED_COMPANY_BUILDING_PRODUCT_DESC: 'company.company_product.assignedCompanyBuildingProductDesc',
        COMPANY_NEW_COMPANY_PRODUCT_LINK: 'company.new_company_product.pageLink',
        COMPANY_NEW_COMPANY_PRODUCT: 'company.new_company_product.pageTitle',
        COMPANY_NEW_COMPANY_PRODUCT_DESC: 'company.new_company_product.pageDesc',
        COMPANY_ALL_COMPANY_PRODUCT_LINK: 'company.all_company_product.pageLink',
        COMPANY_ALL_COMPANY_PRODUCT: 'company.all_company_product.pageTitle',
        COMPANY_ALL_COMPANY_PRODUCT_DESC: 'company.all_company_product.pageDesc',
        COMPANY_COMPANY_BUILDING_MODAL_LINK: 'company.company_building_modal.pageLink',
        COMPANY_COMPANY_BUILDING_MODAL: 'company.company_building_modal.pageTitle',
        COMPANY_COMPANY_BUILDING_MODAL_DESC: 'company.company_building_modal.pageDesc',
        COMPANY_EDIT: 'company.edit.pageTitle',
        COMPANY_EDIT_DESC: 'company.edit.pageDesc',
        COMPANY_SHOW: 'company.show.pageTitle',
        COMPANY_SHOW_DESC: 'company.show.pageDesc',
        COMPANY_CREATE: 'company.create.pageTitle',
        COMPANY_CREATE_DESC: 'company.create.pageDesc',
        COMPANY_ACTION_CREATE: 'page.action.create',
        COMPANY_ACTION_CHANGE_PASSWORD: 'page.action.change_password',
        COMPANY_ACTION_EDIT: 'page.action.update',
        COMPANY_SUBSCRIPTION: 'Company Subscription',
        COMPANY_SUBSCRIPTION_LIST: 'Company Subscription List',
        COMPANY_SUBSCRIPTION_EDIT: 'Company Subscription Edit',
        COMPANY_SUBSCRIPTION_LIST_DESC: 'Company Subscription List Desc',
        COMPANY_SUBSCRIPTION_EDIT_DESC: 'Company Subscription Edit Desc',
    },

    API: {
        COMPANY: '/crud/Company',
        COMPANY_BUILDINGS: '/crud/CompanyBuilding',
        COMPANY_ALIAS: '/crud/Company/:alias',
        COMPANY_STATUS: '/changeCompanyStatus',
        COMPANY_SUBSCRIPTION_STATUS: '/changeCompanySubscriptionStatus',
        CITIES: '/crud/City',
        COMPANY_SEARCH : '/crud/Company/search/:query',
        COMPANY_BUILDING: '/crud/CompanyBuilding/all',
        PRODUCT: '/crud/Product/',
        COMPANY_BUILDING_PRODUCT: '/crud/CompanyBuildingProduct',
        COMPANY_BUILDING_PRODUCT_ALIAS: '/crud/CompanyBuildingProduct/:alias',
        COMPANY_PRODUCT: '/crud/CompanyProduct?fieldName=status&value=accepted',
        ALL_COMPANY_PRODUCT: '/crud/CompanyProduct',
        COMPANY_PRODUCTS: '/crud/CompanyProduct?fieldName=status&value=New',
        COMPANY_PRODUCT_STATUS: '/crud/CompanyProduct/status/:new',
        PRODUCT_STATUS: '/crud/CompanyProduct/:alias',
        ASSIGNED_COMPANY_BUILDING_PRODUCT: '/crud/CompanyBuildingProduct',
        FILE_UPLOAD: '/device/companyImage',
        COMPANY_PASSWORD_ALIAS: '/crud/User/:alias',
        ZONES: '/crud/Zone/all',
        ZONES_OWNER_ID:'/device/getObjectsByOwnerId/Zone/:ownerId',
        COMPANY_SUBSCRIPTION: '/crud/CompanySubscription',
        COMPANY_SUBSCRIPTION_LIST: '/device/getSubscriptionsByUser/:alias',
        COMPANY_SUBSCRIPTION_ALIAS: '/crud/CompanySubscription/:alias',
        CLIENT: '/device/getClient',
        CURRENT_VENDOR: '/device/getCurrentOwner',
        CLIENT_MODAL_SUBSCRIPTION: '/device/getCreatedSubscriptions'

    },

     FIELD: {
         NAME: 'device_company.name',
         NAME_FIELD: 'device_company.name',
         EMAIL: 'auth_user.email',
         EMAIL_FIELD: 'auth_user.email',
         PHONE_NUMBER: 'auth_user.phoneNo',
         PHONE_NUMBER_FIELD: 'auth_user.phoneNo',
         PASSWORD: 'password',
         CONFIRM_PASSWORD: 'confirmPassword',
         CODE: '14'
     }
};
