export const CLIENT_CONSTANTS = {
    'URL': {
        CLIENT: '/client',
        CLIENT_LIST: '/client/list',
        CLIENT_EDIT: '/client/edit/',
        CLIENT_SHOW: '/client/show',
        CLIENT_CREATE: '/client/create',
        CLIENT_NEW_CLIENT_PRODUCT: '/client/new-client-product',
        CLIENT_CLIENT_PRODUCT: '/client/client-product',
        CLIENT_NEW_PRODUCT_TYPE_LIST: '/client/new-product-type-list',
        CLIENT_MACHINE_PRODUCT_TYPE: '/client/machine-productType',
        CLIENT_MACHINE_PRODUCT_TYPE_ALIAS: '/client/machine-productType/:alias',
        CLIENT_MACHINE_PRODUCT_TYPE_SHOW: '/client/machine-product-type-show',
        CLIENT_ASSIGNED_VENDOR_PRODUCT: '/client/assigned-vendor-product',
        CLIENT_ASSIGNED_COMPANY_PRODUCT: '/client/assigned-company-product',
        CLIENT_PRODUCT_TYPE_MACHINE: '/client/product-type/machine',
        CLIENT_CHANGE_PASSWORD: '/client/change-password',
        CLIENT_LIST_PRODUCT: '/client/list-product',
        CLIENT_CLIENT_SUBSCRIPTION_LIST: '/client/client-subscription-list',
        CLIENT_SUBSCRIPTION_LIST_ALIAS: '/client/client-subscription-list/:alias',
        CLIENT_CLIENT_SUBSCRIPTION_EDIT: '/client/client-subscription-edit',
    },

    LINK: {
        LIST: 'list',
        CREATE: 'create',
        SHOW: 'show/:alias',
        EDIT: 'edit/:alias',
        NEW_CLIENT_PRODUCT: 'new-client-product',
        CLIENT_PRODUCT: 'client-product',
        NEW_PRODUCT_TYPE_LIST : 'new-product-type-list',
        MACHINE_PRODUCT_TYPE: 'machine-productType',
        ASSIGNED_VENDOR_PRODUCT: 'assigned-vendor-product',
        ASSIGNED_COMPANY_PRODUCT: 'assigned-company-product',
        MACHINE_PRODUCT_TYPE_SHOW: 'machine-product-type-show/:alias',
        PRODUCT_TYPE_MACHINE: 'product-type/machine/:alias',
        CHANGE_PASSWORD: 'change-password/:alias',
        LIST_PRODUCT: 'list-product',
        CLIENT_SUBSCRIPTION_LIST: 'client-subscription-list/:alias',
        CLIENT_SUBSCRIPTION_EDIT: 'client-subscription-edit/:alias'
    },

    LABEL: {
        CLIENT: 'Client',
        CLIENT_SUBSCRIPTION: 'Client Subscription',
        CLIENT_SUBSCRIPTION_LIST: 'Client Subscription List',
        CLIENT_SUBSCRIPTION_LIST_DESC: 'Client Subscription List Desc',
        PRODUCT: 'Product',
        PRODUCT_LIST: 'Product List',
        PRODUCT_LIST_DESC: 'Product List Desc',
        CLIENT_PASSWORD: 'Client Password',
        MACHINE_PRODUCT_TYPE: 'Machine Product Type',
        CLIENT_IMAGE: 'Image',
        CLIENT_IMAGES: 'Image',
        COMPANY_PRODUCT: 'Company Product',
        ASSIGNED_COMPANY_PRODUCT: 'Assigned Company Product',
        ASSIGNED_COMPANY_PRODUCT_LIST: 'Assigned Company Product List',
        ASSIGNED_COMPANY_PRODUCT_LIST_DESC: 'Assigned Company Product List Desc',
        BOARD_PRODUCT_TYPE: 'Board Product Type',
        ASSIGNED_VENDOR_PRODUCT: 'Assigned Vendor Product',
        ASSIGNED_VENDOR_PRODUCT_LIST: 'Assigned Vendor Product List',
        CLIENT_MACHINE_PRODUCT_TYPE_LINK: 'client.list.machineProductType',
        ASSIGNED_COMPANY_PRODUCT_LIST_LINK: 'client.list.assignedCompanyProduct',
        VENDOR_PRODUCT: 'Vendor Product',
        CLIENT_VENDOR_PRODUCT: 'Client Vendor Product',
        CLIENT_LIST_LINK: 'client.list.pageLink',
        MACHINE_PRODUCT_LINK: 'client.list.machineProduct',
        CLIENT_PRODUCT_LINK: 'client.list.clientProduct',
        NEW_CLIENT_PRODUCT_LINK: 'client.list.newClientProduct',
        CLIENT_LIST: 'client.list.pageTitle',
        CLIENT_LIST_DESC: 'client.list.pageDesc',
        CLIENT_EDIT_LINK: 'client.edit.pageLink',
        CLIENT_SUBSCRIPTION_EDIT_LINK: 'Client Subscription Edit',
        CLIENT_EDIT: 'client.edit.pageTitle',
        CLIENT_EDIT_DESC: 'client.edit.pageDesc',
        CLIENT_VENDOR_PRODUCT_DESC: 'client.edit.vendorProductDesc',
        CLIENT_SHOW_LINK: 'client.show.pageLink',
        CLIENT_SHOW: 'client.show.pageTitle',
        CLIENT_SHOW_DESC: 'client.show.pageDesc',
        CLIENT_CREATE_LINK: 'client.create.pageLink',
        CLIENT_CREATE: 'client.create.pageTitle',
        CLIENT_CREATE_DESC: 'client.create.pageDesc',
        CLIENT_ACTION_CREATE: 'page.action.create',
        CLIENT_ACTION_CHANGE_PASSWORD: 'page.action.change_password',
        CLIENT_ACTION_EDIT: 'page.action.update',
        CLIENT_NEW_PRODUCT_TYPE_LIST_LINK: 'client.newProductTypeList.pageLink',
        CLIENT_NEW_PRODUCT_TYPE_LIST: 'client.newProductTypeList.pageTitle',
        CLIENT_NEW_PRODUCT_TYPE_LIST_DESC: 'client.newProductTypeList.pageDesc',
        CLIENT_CHANGE_PASSWORD: 'client.changePassword.pageDesc',
        CLIENT_CHANGE_PASSWORD_DESC: 'client.changePassword.pageDesc',
        CLIENT_CHANGE_PASSWORD_LINK: 'client.form.changePasswordLink',
        BOARD_PRODUCT_TYPE_LIST_LINK: 'client.boardProductType.pageLink',
        BOARD_PRODUCT_TYPE_LIST: 'client.boardProductType.pageTitle',
        BOARD_PRODUCT_TYPE_LIST_DESC: 'client.boardProductType.pageDesc',
        MACHINE_PRODUCT_TYPE_LIST_LINK: 'client.machineProductType.pageLink',
        MACHINE_PRODUCT_TYPE_LIST: 'client.machineProductType.pageTitle',
        MACHINE_PRODUCT_TYPE_LIST_DESC: 'client.machineProductType.pageDesc',
        CLIENT_SUBSCRIPTION_EDIT: 'Client Subscription Edit',
        CLIENT_SUBSCRIPTION_EDIT_DESC: 'Client Subscription Edit Desc',
        CLIENT_SUBSCRIPTION_LIST_LINK: 'Client Subscription List'
    },
    API: {
        CLIENT: '/crud/Client',
        CLIENT_ALIAS: '/crud/Client/:alias',
        CLIENT_SUBSCRIPTION_ALIAS: '/crud/ClientSubscription/:alias',
        CLIENT_PASSWORD_ALIAS: '/crud/User/:alias',
        CLIENT_STATUS: '/changeClientStatus',
        SEARCH_CLIENT: '/crud/Client/search/:query',
        CITIES: '/crud/City',
        PRODUCT_TYPE_ALIAS: '/crud/ProductType/:alias',
        CLIENT_PRODUCT : '/crud/ClientProduct',
        BOARD_PRODUCT_TYPE_ALIAS : '/crud/BoardProductType/:alias',
        MACHINE_PRODUCT_TYPE_ALIAS : '/crud/MachineProductType/:alias',
        MACHINE_PRODUCT_TYPE : '/crud/MachineProductType',
        BOARD_PRODUCT_TYPE : '/crud/BoardProductType',
        PRODUCT_STATUS: '/crud/ClientProduct/:alias',
        BOARD_PRODUCT_TYPE_STATUS: '/crud/BoardProductType/:alias',
        MACHINE_PRODUCT_TYPE_STATUS: '/crud/MachineProductType/:alias',
        COMPANY: '/crud/Company',
        COMPANIES: '/crud/Company/all',
        VENDOR: '/crud/Vendor',
        VENDORS: '/crud/Vendor/all',
        COMPANY_PRODUCT: '/crud/CompanyProduct',
        VENDOR_PRODUCT: '/crud/VendorProduct',
        PRODUCTS: '/crud/Product/all',
        PRODUCT_TYPES: '/crud/ProductType/all',
        PRODUCT_TYPE: '/crud/ProductType',
        BOARD_MANUFACTURER: '/crud/BoardManufacturer',
        BOARD_MANUFACTURERS: '/crud/BoardManufacturer/all',
        MANUFACTURERS: '/crud/Manufacturer/all',
        MANUFACTURER: '/crud/Manufacturer',
        MACHINES: '/crud/Machine/all',
        MACHINE: '/crud/Machine',
        ASSIGNED_COMPANY_PRODUCT: '/crud/CompanyProduct',
        ASSIGNED_VENDOR_PRODUCT: '/crud/VendorProduct',
        FILE_UPLOAD: '/device/clientImage',
        PRODUCT: '/crud/Product',
        CLIENT_SUBSCRIPTION_LIST: '/device/getSubscriptionsByUser/:alias',
        CLIENT_INVOICE: '/device/getPendingInvoices/:target',
        PRODUCT_INVOICE: '/device/getPendingInvoices/:alias',
        CLIENT_SUBSCRIPTION: '/crud/ClientSubscription',
        CLIENT_SUBSCRIPTION_STATUS: '/changeClientSubscriptionStatus',
        CLIENTS: '/device/getClient',
        CLIENT_MODAL_SUBSCRIPTION: '/device/getCreatedSubscriptions'

    },

    FIELD: {
        NAME: 'device_client.name',
        NAME_FIELD: 'device_client.name',
        EMAIL: 'auth_user.email',
        EMAIL_FIELD: 'auth_user.email',
        PHONE_NUMBER: 'auth_user.phoneNo',
        PHONE_NUMBER_FIELD: 'auth_user.phoneNo',
        USERNAME: 'username',
        PASSWORD: 'password',
        CONFIRM_PASSWORD: 'confirmPassword'
    }
};
