export const RESOURCES_CONSTANTS = {
    "URL": {
        RESOURCES: '/resources',
        RESOURCES_MEDIA: '/resources/media',
        RESOURCES_FOTA: '/resources/fota',
        RESOURCES_TELEMETRIC_DATA: '/resources/telemetric-data',
        RESOURCES_ERROR_DATA: '/resources/error-data',
        RESOURCES_QRCODE: '/resources/qrcode',

    },

    LINK:{
        MEDIA: 'media',
        FOTA: 'fota',
        TELEMETRIC_DATA: 'telemetric-data',
        ERROR_DATA: 'error-data',
        QRCODE: 'qrcode',

    },

    LABEL: {
        RESOURCES: "Resources",
        PRODUCT: "Product",
        PRODUCT_LIST: "Product List",
        PRODUCT_LIST_DESC: "Product List Desc",
        RESOURCES_PASSWORD: "Resources Password",
        MACHINE_PRODUCT_TYPE: "Machine Product Type",
        RESOURCES_IMAGE: "Image",
        RESOURCES_IMAGES: "Image",
        RESOURCES_COMPANY_LIST_LINK: "resources.list.pageLink",
        MACHINE_PRODUCT_LINK: "resources.list.machineProduct",
        RESOURCES_PRODUCT_LINK: "resources.list.resourcesProduct",
        NEW_RESOURCES_PRODUCT_LINK: "resources.list.newResourcesProduct",
        RESOURCES_COMPANY_LIST: "resources.list.pageTitle",
        RESOURCES_COMPANY_LIST_DESC: "resources.list.pageDesc",
        RESOURCES_EDIT_LINK: "resources.edit.pageLink",
        RESOURCES_EDIT: "resources.edit.pageTitle",
        RESOURCES_EDIT_DESC: "resources.edit.pageDesc",
        RESOURCES_VENDOR_PRODUCT_DESC: "resources.edit.vendorProductDesc",
        RESOURCES_SHOW_LINK: "resources.show.pageLink",
        RESOURCES_SHOW: "resources.show.pageTitle",
        RESOURCES_SHOW_DESC: "resources.show.pageDesc",
        RESOURCES_CREATE_LINK: "resources.create.pageLink",
        RESOURCES_CREATE: "resources.create.pageTitle",
        RESOURCES_CREATE_DESC: "resources.create.pageDesc",
        RESOURCES_ACTION_CREATE:'page.action.create',
        RESOURCES_ACTION_CHANGE_PASSWORD:'page.action.change_password',
        RESOURCES_ACTION_EDIT:'page.action.update',
        RESOURCES_MEDIA_LINK:'resources.list.media',
        RESOURCES_FOTA_LINK:'resources.list.fota',
        RESOURCES_QRCODE_LINK:'resources.list.qrCode',
        RESOURCES_ERROR_DATA_LINK:'resources.list.errorData',
        RESOURCES_TELEMETRIC_DATA_LINK:'resources.list.telemetricData',
        RESOURCES_CHANGE_PASSWORD: "resources.changePassword.pageDesc",
        RESOURCES_CHANGE_PASSWORD_DESC: "resources.changePassword.pageDesc",
        RESOURCES_CHANGE_PASSWORD_LINK: "resources.form.changePasswordLink",


    },
    API:{
        RESOURCE: '/crud/Resources',
        RESOURCES: '/crud/Resources/all',
        RESOURCES_ALIAS: '/crud/Resources/:alias',
        RESOURCES_PASSWORD_ALIAS: '/crud/User/:alias',
        RESOURCES_STATUS: '/changeResourcesStatus',
        SEARCH_RESOURCES:'/crud/Resources/search/:query',
        FILE_UPLOAD:'/device/resourcesImage',
        CITIES:'/crud/City/all',
        DISTRIBUTOR:'/crud/Distributor',
        DISTRIBUTORS:'/crud/Distributor/all',
        COMPANY:'/crud/Company',
        COMPANIES:'/crud/Company/all',
        VENDOR:'/crud/Vendor',
        VENDORS:'/crud/Vendor/all',
        PRODUCT_TYPE:'/crud/ProductType',
        PRODUCT_TYPES:'/crud/ProductType/all',
        PRODUCTS:'/crud/Product/all',
        MACHINE:'/crud/Machine',
        MACHINES:'/crud/Machine/all',
        ZONE:'/crud/Zone',
        ZONES:'/crud/Zone/all',
        COMPANY_BUILDINGS_DATA_COMPANY: '/crud/CompanyBuilding/all',
        COMPANY_BUILDING: '/crud/CompanyBuilding/all',
        ALL_COMPANY_BUILDING_PRODUCT: '/crud/CompanyBuildingProduct',
        COMPANY_BUILDING_PRODUCT_STATUS: '/crud/CompanyBuildingProduct/:alias',
        DOWNLOAD_PRODUCT_DATA_ALIAS:'/device/downloadProductDataByProductId/:alias',
        COMPANY_BUILDING_PRODUCTS:'/device/getCurrentBuildingProduct',
        COMPANY_PRODUCTS:'/device/getCurrentCompanyProduct',
        //DISTRIBUTORS_PRODUCTS:'/device/getCurrentDistributorProduct',
        DISTRIBUTOR_PRODUCTS:'/crud/DistributorProduct/all',
        //VENDORS_PRODUCTS:'/crud/VendorProduct/all',
        PRODUCT_DATA_ALIAS:'/device/getProductDataByProductId/:alias',
        PRODUCT_PRODUCT_TYPE_ALIAS:'/device/getProductByProductTypeId/:alias',
        PRODUCT:'/crud/Product',
        BUILDINGS:'/crud/CompanyBuilding/all',
        VENDOR_DATA:'/resources/getData',
        DISTRIBUTOR_DATA:'/resources/getData',
        DISTRIBUTORS_PRODUCTS:'/device/getCurrentDistributorProduct',
        VENDORS_PRODUCTS:'/device/getCurrentVendorProduct',
        COMPANY_BUILDINGS:'/device/getCompanyBuildingByCompanyId/:companyAlias',
        COMPANY_DATA:'/resources/getData',
        CLIENT_DATA:'/resources/getData',
        COMPANY_BUILDING_DATA:'/resources/getData',
        COMPANY_PRODUCT:'/crud/CompanyProduct/all',
        CLIENT_PRODUCT:'/crud/ClientProduct/all',
        VENDOR_PRODUCTS:'/crud/VendorProduct/all',
        COMPANY_BUILDING_PRODUCT:'/crud/CompanyBuildingProduct/all',
        DOWNLOAD_DATA:'/resources/downloadData',
        COMPANY_BUILDING_LIST:'/device/getObjectsByOwnerId/CompanyBuilding/:ownerId',
        COMPANY_LIST:'/device/getObjectsByOwnerId/Company/:ownerId',
        MACHINE_BY_BUILDING:'/device/getObjectsByOwnerId/CompanyBuildingProduct/:ownerId',
        CURRENT_PRODUCT_TYPE:'/device/getAllProductTypes',
        CURRENT_CATEGORY:'/crud/ProductCategory/all',
        PRODUCT_BY_COMPANY_BUILDING:'/device/getObjectsByOwnerId/CompanyBuildingProduct/:ownerId',
        PRODUCT_BY_COMPANY_BUILDING_AND_PRODUCT_TYPE:'/device/getCompanyBuildingProducts/:ownerId/:productTypeId',
        DISTRIBUTOR_LIST:'/device/getObjectsByOwnerId/Distributor/:ownerId',
        MEDIA_PRODUCT_TYPE_ALIAS:'/device/getMediaByProductTypeId/:alias',
        FIRMWARE_TYPE_MEDIA:'/device/getFirmwareMediaByProductTypeId/:alias',
        VENDOR_OF_CLIENT:'/crud/Vendor/all',
        COMPANY_OF_CLIENT:'/crud/Company/all',
        CLIENT_VENDOR_DATA:'/resources/getData',
        CLIENT_COMPANY_DATA:'/resources/getData',
        FOTAS:'/crud/Firmware/all',
        ERROR_DATAS:'/crud/ErrorData/all',
        TELEMETRIC_DATAS:'/crud/TelemetricData/all',
        MEDIAS:'/crud/Media/all',
        CLIENT: '/device/getClient',
        MEDIA_RESOURCES: '/device/getMediaByProductTypeId/:alias',
        FOTA_RESOURCES: '/device/getFirmwareMediaByProductType',
        TELEMETRIC_RESOURCES: '/device/getTelemetricDataByProductId/:alias',
        ERROR_RESOURCES: '/device/getErrorDataByProductId/:alias',
        COMPONENT: '/crud/Component/all',

    },

    FIELD:{
        NAME: "name",
        NAME_FIELD: "name",
        EMAIL: "email",
        EMAIL_FIELD: "email",
        PHONE_NUMBER: "phoneNo",
        PHONE_NUMBER_FIELD: "phoneNo",
        USERNAME: "username",
        PASSWORD: "password",
        CONFIRM_PASSWORD:"confirmPassword"
    }
};
