export const PRODUCT_TYPE_CONSTANTS = {
    'URL': {
         PRODUCT_TYPE: '/product-type',
         PRODUCT_TYPE_LIST: '/product-type/list',
         PRODUCT_TYPE_CREATE: '/product-type/create',
         PRODUCT_TYPE_EDIT: '/product-type/edit',
         PRODUCT_TYPE_SHOW: '/product-type/show',
         PRODUCT_TYPE_PRODUCT_TYPE_BOARD: '/product-type/product-type-board',
         PRODUCT_TYPE_PRODUCT_TYPE_BOARD_ALIAS: '/product-type/product-type-board/:alias',
         PRODUCT_TYPE_PRODUCT_LIST: '/product-type/product/list',
         PRODUCT_TYPE_PRODUCT_LIST_ALIAS: '/product-type/product/list/:alias',
         PRODUCT_TYPE_MEDIA_LIST: '/product-type/media/list',
         PRODUCT_TYPE_MEDIA_LIST_ALIAS: '/product-type/media/list/:alias',
         PRODUCT_TYPE_PRODUCT_TYPE_MACHINE: '/product-type/product-type-machine',
         PRODUCT_TYPE_PRODUCT_TYPE_MACHINE_ALIAS: '/product-type/product-type-machine/:alias',
         PRODUCT_TYPE_BOARDS: '/product-type/boards',
         PRODUCT_TYPE_BOARDS_ALIAS: '/product-type/boards/:alias',
         PRODUCT_TYPE_MACHINES: '/product-type/machines',
         PRODUCT_TYPE_MACHINES_ALIAS: '/product-type/machines/:alias',
         PRODUCT_TYPE_FIRMWARE_LIST: '/product-type/firmware/list',
         PRODUCT_TYPE_FIRMWARE_LIST_ALIAS: '/product-type/firmware/list/:alias',
    },
    LINK: {
        LIST: 'list',
        SHOW: 'show/:alias',
        CREATE: 'create',
        EDIT: 'edit/:alias',
        PRODUCT_TYPE_BOARD: 'product-type-board/:alias',
        PRODUCT_TYPE_MACHINE: 'product-type-machine/:alias',
        PRODUCT_LIST: 'product/list/:alias',
        MEDIA_LIST: 'media/list/:alias',
        BOARDS: 'boards/:alias',
        MACHINES: 'machines/:alias',
        FIRMWARE_LIST: 'firmware/list/:alias'

    },
    LABEL: {
        PRODUCT_TYPE: 'ProductType',
        PRODUCT_TYPE_IMAGE: 'Image',
        PRODUCT_TYPE_ADMIN: 'ProductTypeAdmin',
        PRODUCT_TYPE_LIST_LINK: 'productType.list.pageLink',
        PRODUCT_TYPE_LIST: 'productType.list.pageTitle',
        PRODUCT_TYPE_LIST_DESC: 'productType.list.pageDesc',
        PRODUCT_TYPE_EDIT: 'productType.edit.pageTitle',
        PRODUCT_TYPE_EDIT_DESC: 'productType.edit.pageDesc',
        PRODUCT_TYPE_SHOW: 'productType.show.pageTitle',
        PRODUCT_TYPE_SHOW_DESC: 'productType.show.pageDesc',
        PRODUCT_TYPE_ACTION_CREATE: 'page.action.create',
        PRODUCT_TYPE_ACTION_CHANGE_PASSWORD: 'page.action.change_password',
        PRODUCT_TYPE_ACTION_EDIT: 'page.action.update',
        PRODUCT_TYPE_CREATE: 'productType.create.pageTitle',
        PRODUCT_TYPE_CREATE_DESC: 'productType.create.pageDesc',
        PRODUCT_TYPE_SHOW_COMPANY_PRODUCT_TYPE_LINK: 'productType.show-company-productType.pageLink',
        PRODUCT_TYPE_SHOW_COMPANY_PRODUCT_TYPE: 'productType.show-company-productType.pageTitle',
        PRODUCT_TYPE_SHOW_COMPANY_PRODUCT_TYPE_DESC: 'productType.show-company-productType.pageDesc',
        PRODUCT_TYPE_SHOW_ADMIN_LINK: 'productType.show-admin.pageLink',
        PRODUCT_TYPE_SHOW_ADMIN: 'productType.show-admin.pageTitle',
        PRODUCT_TYPE_SHOW_ADMIN_DESC: 'productType.show-admin.pageDesc',
        BOARD: 'Board',
        PRODUCT_TYPE_BOARD: 'Board Manufacturer',
        PRODUCT_TYPE_MACHINE: 'Machine Manufacturer',
        BOARD_LIST: 'Board List',
        BOARD_LIST_DESC: 'Board List Desc',
        PRODUCT_TYPE_BOARDS: 'Board',
        PRODUCT_TYPE_BOARD_LIST_LINK: 'Product type-Board',
        MACHINE: 'MACHINE',
        MACHINE_LIST: 'MACHINE List',
        MACHINE_LIST_DESC: 'MACHINE List Desc',
        PRODUCT_TYPE_MACHINES: 'Machine',
        PRODUCT_TYPE_MACHINE_LIST_LINK: 'Product-type-Machine'

    },
    API: {
        PRODUCT_TYPE: '/crud/ProductType',
        BOARD_PRODUCT_TYPE: '/device/getBoardByProductTypeId/:alias',
        // PRODUCT_TYPE: '/crud/ProductType?fieldName=status&value=New',
        PRODUCT_TYPE_ALIAS: '/crud/ProductType/:alias',
        SEARCH_PRODUCT_TYPE: '/crud/ProductType/search/:query',
        PRODUCT_TYPE_BY_COMPANY_ID: '/company/getProductTypeByCompanyId/:id',
        PRODUCT_TYPE_BY_ADMIN: '/company/getProductTypeAdminByProductTypeId/:id',
        PRODUCT_TYPE_ADMIN: '/crud/ProductTypeAdmin',
        PRODUCT_TYPE_ADMIN_ID: '/crud/ProductTypeAdmin/:id',
        SEARCH_PRODUCT_TYPE_ADMIN: '/crud/ProductTypeAdmin/search/:query',
        PRODUCT_TYPE_STATUS: '/crud/productType/status/:new',
        PRODUCT_TYPES: '/crud/productType/all',
        BOARDS: '/crud/Board/all',
        BOARD: '/crud/Board',
        IMAGE_UPLOAD: '/device/productTypeImage',
        FILE_UPLOAD: '/device/productTypeFile',
        PRODUCT_CATEGORY: '/crud/ProductCategory',
        PRODUCT_CATEGORYS: '/crud/ProductCategory/all',
        PRODUCT_CATEGORY_ALIAS: '/crud/ProductCategory/:alias',
        COMPONENT: '/crud/Component/all',
        CLIENT: '/device/getClient',
        COMPONENT_IMAGE_UPLOAD: '/device/componentImage',
        SUBSCRIPTION: '/device/getCurrentSubscriptions',
        BOARD_PRODUCT_TYPE_BY_PRODUCT_TYPE: '/device/getBoardProductTypeByProductTypeId/:alias',
        MACHINE_PRODUCT_TYPE_BY_PRODUCT_TYPE: '/device/getMachineProductTypeByProductTypeId/:alias',
        BOARD_BOARD_PRODUCT_TYPE: '/device/getBoardByBoardProductTypeId/:alias',
        MACHINE_MACHINE_PRODUCT_TYPE: '/device/getMachineByMachineProductTypeId/:alias',
        ALL_BOARD: '/crud/Board/all',
        MACHINE_PRODUCT_TYPE: '/crud/MachineProductType/:alias',
        BOARD_PRODUCT_TYPE_DATA: '/crud/BoardProductType/:alias',
        BOARD_STATUS: '/crud/Board/:alias',
        MACHINE_STATUS: '/crud/Machine/:alias',
        CURRENT_SUBSCRIPTIONS: '/device/getCurrentSubscriptions',

    },

    FIELD: {
         NAME: 'device_producttype.name',
         USERNAME: 'username',
         CODE: '14'
    }
};

