export const DISTRIBUTOR_CONSTANTS = {
    'URL': {
         DISTRIBUTOR: '/distributor',
         DISTRIBUTOR_LIST: '/distributor/list',
         DISTRIBUTOR_EDIT: '/distributor/edit/',
         DISTRIBUTOR_SHOW: '/distributor/show',
         DISTRIBUTOR_CREATE: '/distributor/create',
         DISTRIBUTOR_NEW_DISTRIBUTOR_PRODUCT: '/distributor/new-distributor-product',
         DISTRIBUTOR_DISTRIBUTOR_PRODUCT: '/distributor/distributor-product',
         DISTRIBUTOR_ALL_DISTRIBUTOR_PRODUCT: '/distributor/all-distributor-product',
         DISTRIBUTOR_ASSIGNED_COMPANY_PRODUCT: '/distributor/assigned-company-product',
         PRODUCT_TELEMETRIC_DATA: '/product/telemetric-data',
         PRODUCT_ERROR_DATA: '/product/error-data',
         DISTRIBUTOR_CHANGE_PASSWORD: '/distributor/change-password',
         DISTRIBUTOR_DISTRIBUTOR_SUBSCRIPTION_LIST: '/distributor/distributor-subscription-list',
         DISTRIBUTOR_SUBSCRIPTION_LIST_ALIAS: '/distributor/distributor-subscription-list/:alias',
         DISTRIBUTOR_DISTRIBUTOR_SUBSCRIPTION_EDIT: '/distributor/distributor-subscription-edit'


    },

    LINK: {
        LIST: 'list',
        CREATE: 'create',
        SHOW: 'show/:alias',
        EDIT: 'edit/:alias',
        NEW_DISTRIBUTOR_PRODUCT: 'new-distributor-product',
        DISTRIBUTOR_PRODUCT: 'distributor-product',
        ALL_DISTRIBUTOR_PRODUCT: 'all-distributor-product',
        ASSIGNED_COMPANY_PRODUCT: 'assigned-company-product',
        TELEMETRIC_DATA: 'telemetric-data/:alias',
        ERROR_DATA: 'error-data/:alias',
        CHANGE_PASSWORD: 'change-password/:alias',
        DISTRIBUTOR_SUBSCRIPTION_LIST: 'distributor-subscription-list/:alias',
        DISTRIBUTOR_SUBSCRIPTION_EDIT: 'distributor-subscription-edit/:alias'

    },

    LABEL: {
        DISTRIBUTOR: 'Distributor',
        ALL_DISTRIBUTOR_LIST_LINK: 'All Distributor Product',
        DISTRIBUTOR_PASSWORD: 'Distributor Password',
        DISTRIBUTOR_CHANGE_PASSWORD: 'Distributor Change Password',
        DISTRIBUTOR_CHANGE_PASSWORD_DESC: 'Distributor Change Password Description',
        DISTRIBUTOR_CHANGE_PASSWORD_LINK: 'Change Password',
        DISTRIBUTOR_IMAGE: 'Image',
        ASSIGNED_COMPANY_PRODUCT: 'Assigned Company Product',
        COMPANY_PRODUCT: 'Company Product',
        DISTRIBUTOR_USER: 'DistributorUser',
        DISTRIBUTOR_ADMIN: 'DistributorAdmin',
        DISTRIBUTOR_LIST_LINK: 'distributor.list.pageLink',
        DISTRIBUTOR_PRODUCT_LIST_LINK: 'distributor.list.distributorProductList',
        NEW_DISTRIBUTOR_PRODUCT_LIST_LINK: 'distributor.list.newDistributorProductPageLink',
        DISTRIBUTOR_LIST: 'distributor.list.pageTitle',
        ASSIGNED_DISTRIBUTOR_PRODUCT_LIST_LINK: 'distributor.list.assignedDistributorProductListLink',
        ASSIGNED_COMPANY_PRODUCT_LIST: 'distributor.list.assignedDistributorProductList',
        DISTRIBUTOR_LIST_DESC: 'distributor.list.pageDesc',
        ASSIGNED_COMPANY_PRODUCT_LIST_DESC: 'distributor.list.assignedDistributorProductListDesc',
        DISTRIBUTOR_EDIT: 'distributor.edit.pageTitle',
        DISTRIBUTOR_EDIT_DESC: 'distributor.edit.pageDesc',
        DISTRIBUTOR_SHOW: 'distributor.show.pageTitle',
        DISTRIBUTOR_SHOW_DESC: 'distributor.show.pageDesc',
        DISTRIBUTOR_CREATE: 'distributor.create.pageTitle',
        DISTRIBUTOR_CREATE_DESC: 'distributor.create.pageDesc',
        DISTRIBUTOR_ACTION_CREATE: 'page.action.create',
        DISTRIBUTOR_ACTION_CHANGE_PASSWORD: 'page.action.change_password',
        DISTRIBUTOR_ACTION_EDIT: 'page.action.update',
        DISTRIBUTOR_NEW_DISTRIBUTOR_PRODUCT_LINK: 'distributor.newDistributorProduct.pageLink',
        DISTRIBUTOR_NEW_DISTRIBUTOR_PRODUCT: 'distributor.newDistributorProduct.pageTitle',
        DISTRIBUTOR_NEW_DISTRIBUTOR_PRODUCT_DESC: 'distributor.newDistributorProduct.pageDesc',
        DISTRIBUTOR_DISTRIBUTOR_PRODUCT_LINK: 'distributor.distributorProduct.pageLink',
        DISTRIBUTOR_DISTRIBUTOR_PRODUCT: 'distributor.distributorProduct.pageTitle',
        DISTRIBUTOR_DISTRIBUTOR_PRODUCT_DESC: 'distributor.distributorProduct.pageDesc',
        DISTRIBUTOR_ALL_DISTRIBUTOR_PRODUCT_LINK: 'distributor.AllDistributorProduct.pageLink',
        DISTRIBUTOR_ALL_DISTRIBUTOR_PRODUCT: 'distributor.AllDistributorProduct.pageTitle',
        DISTRIBUTOR_ALL_DISTRIBUTOR_PRODUCT_DESC: 'distributor.AllDistributorProduct.pageDesc',
        DISTRIBUTOR_SUBSCRIPTION: 'Distributor Subscription',
        DISTRIBUTOR_SUBSCRIPTION_LIST: 'Distributor Subscription List',
        DISTRIBUTOR_SUBSCRIPTION_EDIT: 'Distributor Subscription Edit',
        DISTRIBUTOR_SUBSCRIPTION_LIST_DESC: 'Distributor Subscription List Desc',
        DISTRIBUTOR_SUBSCRIPTION_EDIT_DESC: 'Distributor Subscription Edit Desc'
    },

    API: {
        DISTRIBUTOR: '/crud/Distributor',
        DISTRIBUTOR_ALIAS: '/crud/Distributor/:alias',
        DISTRIBUTOR_SUBSCRIPTION_ALIAS: '/crud/DistributorSubscription/:alias',
        DISTRIBUTOR_STATUS: '/changeDistributorStatus',
        SEARCH_DISTRIBUTOR: '/crud/Distributor/search/:query',
        CITIES: '/crud/City',
        PRODUCTS: '/crud/Product',
        PRODUCT: '/crud/Product/all',
        DISTRIBUTOR_PRODUCT: '/crud/DistributorProduct?fieldName=status&value=Accepted',
        DISTRIBUTOR_PRODUCTS: '/crud/DistributorProduct?fieldName=status&value=New',
        COMPANIES: '/crud/Company',
        COMPANY: '/crud/Company/all',
        COMPANY_PRODUCTS: '/crud/CompanyProduct/all',
        COMPANY_PRODUCT: '/crud/CompanyProduct',
        PRODUCT_STATUS: '/crud/DistributorProduct/:alias',
        ALL_DISTRIBUTOR_PRODUCT: '/crud/DistributorProduct',
        COMPANY_PRODUCT_STATUS: '/crud/CompanyProduct/status/:new',
        ASSIGNED_COMPANY_PRODUCT: '/crud/CompanyProduct',
        FILE_UPLOAD: '/device/distributorImage',
        DISTRIBUTOR_SUBSCRIPTION: '/crud/DistributorSubscription',
        DISTRIBUTOR_SUBSCRIPTION_LIST: '/device/getSubscriptionsByUser/:alias',
        DISTRIBUTOR_SUBSCRIPTION_STATUS: '/changeDistributorSubscriptionStatus',
        DISTRIBUTOR_PASSWORD_ALIAS: '/crud/User/:alias',
        PRODUCT_INVOICE: '/device/getPendingInvoices/:alias',
        CLIENT: '/device/getClient',
        CLIENT_MODAL_SUBSCRIPTION: '/device/getCreatedSubscriptions'

    },

    FIELD: {
        NAME: 'device_distributor.name',
        NAME_FIELD: 'name',
        EMAIL: 'auth_user.email',
        EMAIL_FIELD: 'email',
        PHONE_NUMBER: 'auth_user.phoneNo',
        PHONE_NUMBER_FIELD: 'phoneNo',
        PASSWORD: 'password',
        CONFIRM_PASSWORD: 'confirmPassword'
    }
};
