export const PRODUCT_CONSTANTS = {
    'URL': {
         PRODUCT: '/product',
         PRODUCT_PRODUCT_LIST: '/product/product-list',
         PRODUCT_PRODUCT_LIST_ALIAS: '/product/product-list/:alias',
         PRODUCT_PRODUCT_DATA_LIST: '/product/product-data-list',
         PRODUCT_SHOW: '/product/show',
         PRODUCT_CREATE: '/product/create',
         PRODUCT_EDIT: '/product/edit',
         PRODUCT_TELEMETRIC_DATA: '/product/telemetric-data',
         PRODUCT_ERROR_DATA: '/product/error-data',

    },

    LINK: {
        PRODUCT_LIST: 'product-list',
        PRODUCT_DATA_LIST: 'product-data-list/:alias',
        SHOW: 'show/:alias',
        CREATE: 'create/:alias',
        EDIT: 'edit/:alias',
        TELEMETRIC_DATA: 'telemetric-data/:alias',
        ERROR_DATA: 'error-data/:alias',
        ASSIGNED_VENDOR_PRODUCT: 'assigned-vendor-product',
        ASSIGNED_COMPANY_PRODUCT: 'assigned-company-product',
        ASSIGNED_COMPANY_BUILDING_PRODUCT: 'assigned-company-building-product',
        ASSIGNED_DISTRIBUTOR_PRODUCT: 'assigned-distributor-product',

    },

    LABEL: {
        PRODUCT: 'Product',
        BOARD_ORDER: 'Board Order',
        MACHINE_ORDER: 'Machine Order',
        PRODUCT_ASSIGNMENT: 'Product Assignment',
        PRODUCT_DATA_LIST: 'Product Data List',
        PRODUCT_IMAGE: 'Image',
        PRODUCT_ADMIN: 'ProductAdmin',
        PRODUCT_LIST_LINK: 'product.list.pageLink',
        PRODUCT_LIST: 'product.list.pageTitle',
        PRODUCT_LIST_DESC: 'product.list.pageDesc',
        PRODUCT_EDIT: 'product.edit.pageTitle',
        PRODUCT_EDIT_DESC: 'product.edit.pageDesc',
        PRODUCT_SHOW: 'product.show.pageTitle',
        PRODUCT_SHOW_DESC: 'product.show.pageDesc',
        PRODUCT_ACTION_CREATE: 'page.action.create',
        PRODUCT_ACTION_CHANGE_PASSWORD: 'page.action.change_password',
        PRODUCT_ACTION_EDIT: 'page.action.update',
        PRODUCT_CREATE: 'product.create.pageTitle',
        PRODUCT_CREATE_DESC: 'product.create.pageDesc',
        PRODUCT_SHOW_COMPANY_PRODUCT_LINK: 'product.show-company-product.pageLink',
        PRODUCT_SHOW_COMPANY_PRODUCT: 'product.show-company-product.pageTitle',
        PRODUCT_SHOW_COMPANY_PRODUCT_DESC: 'product.show-company-product.pageDesc',
        PRODUCT_SHOW_ADMIN_LINK: 'product.show-admin.pageLink',
        PRODUCT_SHOW_ADMIN: 'product.show-admin.pageTitle',
        PRODUCT_SHOW_ADMIN_DESC: 'product.show-admin.pageDesc',
    },

    API: {
        PRODUCT: '/crud/Product?fieldName=status&value=New',
        PRODUCT_ALIAS: '/crud/Product/:alias',
        SEARCH_PRODUCT: '/crud/Product/search/:query',
        PRODUCT_BY_COMPANY_ID: '/company/getProductByCompanyId/:id',
        PRODUCT_BY_ADMIN: '/company/getProductAdminByProductId/:id',
        PRODUCT_ADMIN: '/crud/ProductAdmin',
        PRODUCT_ADMIN_ID: '/crud/ProductAdmin/:id',
        SEARCH_PRODUCT_ADMIN: '/crud/ProductAdmin/search/:query',
        PRODUCT_TYPES: '/crud/ProductType/all',
        PRODUCT_TYPE: '/crud/ProductType',
        CLIENT: '/device/getClient',
        MACHINES_ALIAS: '/device/getMachineByProductTypeId/:alias',
        BOARDS_ALIAS: '/device/getBoardByProductTypeId/:alias',
        MANUFACTURER_PRODUCT: '/crud/ManufacturerProduct',
        BOARD_MANUFACTURER_PRODUCT: '/crud/BoardManufacturerProduct',
        PRODUCT_PRODUCT_TYPE_ALIAS: '/device/getProductByProductTypeId/:alias',
        MANUFACTURERS: '/crud/Manufacturer/all',
        BOARDS: '/crud/Board?fieldName=createdBy&value=true',
        FILE_UPLOAD: '/device/productImage',
        //PRODUCT_DATA_ALIAS: '/device/getProductDataByProductId/:alias',
        PRODUCT_DATA_ALIAS:  '/report/getData',
        DOWNLOAD_PRODUCT_DATA_ALIAS: '/device/downloadProductDataByProductId/:alias',
        DOWNLOAD_DATA: '/report/downloadData',
        CLIENT_SUBSCRIPTION_ALIAS: '/device/getCurrentSubscriptions',
        DOWNLOAD_CLIENT_PRODUCT_DATA: '/report/downloadData',
        BOARD_PRODUCT_TYPE : '/crud/BoardProductType',
        BOARD_MANUFACTURERS: '/crud/BoardManufacturer/all',
        PRODUCT_TYPE_ALIAS: '/crud/ProductType/:alias',
    },

    FIELD: {
        NAME: 'device_product.name',
        EMAIL: 'email',
        USERNAME: 'username',
        PHONE_NO: 'phoneNo',
        CONFIRM_PASSWORD: 'confirmPassword',
        DEVICEID: 'device_product.UK_hdi1h978moqgjhavlwj',
        IMIEID: 'device_product.imieId',
        BOARDID: 'device_product.board',
        MACHINEID: 'device_product.machine',
    }
};
export const PRODUCT_RESOURCES_CONSTANTS = {
    "URL": {
        PRODUCT_RESOURCES_TELEMETRIC_DATA: '/product/telemetric-data/:alias',
        PRODUCT_ERROR_DATA: '/product/error-data/:alias',
        PRODUCT_SHOW: '/product/show/:alias',
    }
}